FROM postgres:16-alpine

RUN apk add --no-cache \
    openssh-client \
    sshpass \
    netcat-openbsd

WORKDIR /backup

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

CMD ["sleep", "infinity"]